### ISSUE TITLE
MalformedURLException when installing scala-cli

### ISSUE THREAD

**Issue by ckipp01** [coursier/apps#120]
🤔 am I doing something wrong with this, when trying out `cs install --contrib scala-cli` on mac I'm met with this when passing in `-v` a couple times:

```
Completing 'org.virtuslab.scala-cli:cli_' (org: org.virtuslab.scala-cli, name: cli)
Found 1 completions:
  cli_2.12
Module org.virtuslab.scala-cli::cli supports 1 scala versions:
  2.12 (found)
Versions for org.virtuslab.scala-cli:cli_2.12: 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8
Checking prebuilt launcher at gz+https://github.com/VirtusLab/scala-cli/releases/download/v0.0.8/scala-cli-x86_64-apple-darwin.gz
Error downloading gz+https://github.com/VirtusLab/scala-cli/releases/download/v0.0.8/scala-cli-x86_64-apple-darwin.gz
Exception in thread "main" coursier.install.InstallDir$DownloadError: Error downloading gz+https://github.com/VirtusLab/scala-cli/releases/download/v0.0.8/scala-cli-x86_64-apple-darwin.gz
        at coursier.install.InstallDir$.handleArtifactErrors(InstallDir.scala:626)
        at coursier.install.InstallDir$.$anonfun$prebuiltOrNotFoundUrls$1(InstallDir.scala:653)
        at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
        at coursier.install.InstallDir$.$anonfun$prebuiltOrNotFoundUrls$6(InstallDir.scala:660)
        at scala.util.Either.flatMap(Either.scala:341)
        at coursier.install.InstallDir$.coursier$install$InstallDir$$prebuiltOrNotFoundUrls(InstallDir.scala:658)
        at coursier.install.InstallDir.update$1(InstallDir.scala:255)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$21(InstallDir.scala:385)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$21$adapted(InstallDir.scala:384)
        at coursier.install.Updatable$.get$1(Updatable.scala:55)
        at coursier.install.Updatable$.$anonfun$writing$1(Updatable.scala:96)
        at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:72)
        at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:98)
        at coursier.install.Updatable$.writing(Updatable.scala:96)
        at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:384)
        at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:87)
        at coursier.cli.install.Install$.$anonfun$run$7(Install.scala:108)
        at coursier.cli.install.Install$.$anonfun$run$7$adapted(Install.scala:95)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at coursier.cli.install.Install$.run(Install.scala:95)
        at coursier.cli.Coursier$.$anonfun$runA$2(Coursier.scala:152)
        at coursier.cli.Coursier$.$anonfun$runA$2$adapted(Coursier.scala:140)
        at coursier.cli.CommandAppPreA.run(CommandAppPreA.scala:22)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5(CommandAppWithPreCommand.scala:99)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$5$adapted(CommandAppWithPreCommand.scala:99)
        at scala.util.Either.fold(Either.scala:191)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3(CommandAppWithPreCommand.scala:99)
        at caseapp.core.app.CommandAppWithPreCommand.$anonfun$main$3$adapted(CommandAppWithPreCommand.scala:85)
        at scala.Option.foreach(Option.scala:407)
        at caseapp.core.app.CommandAppWithPreCommand.main(CommandAppWithPreCommand.scala:85)
        at coursier.cli.Coursier$.main(Coursier.scala:105)
        at coursier.cli.Coursier.main(Coursier.scala)
```

_Originally posted by @ckipp01 in https://github.com/coursier/apps/issues/115#issuecomment-969963802_

**Comment by ckipp01** [comment]
NOTE: from the convo in the pr:

> @ckipp01 This should work with the latest nightly (2.0.16-200-ge888c6dea).

> @lwronski This is fixed on the coursier master by coursier/coursier#2265. This should work fine with the next coursier nightly.

I'll still keep this open for now until the next coursier release just in case people hit on this.
