### ISSUE TITLE
Unable to cs install mill

### ISSUE THREAD

**Issue by ckipp01** [coursier/apps#17]
I wasn't sure if this was better reported here or in the mill repo, so if it's a better fit there, let me know and I'll submit there.

Currently a user is unable to do either a `cs update mill` or `cs install mill`. They are created with the following:

```
❯ cs install mill
https://repo1.maven.org/maven2/io/get-coursier/apps/maven-metadata.xml
  No new update since 2020-04-18 12:10:23
https://repo1.maven.org/maven2/com/lihaoyi/mill-dev_2.13/maven-metadata.xml
  No new update since 2020-04-17 14:04:05
Exception in thread "main" coursier.error.ResolutionError$CantDownloadModule: Error downloading com.lihaoyi:mill-dev_2.13:latest.stable
  No latest stable version found in https://repo1.maven.org/maven2/com/lihaoyi/mill-dev_2.13/maven-metadata.xml
	at coursier.Resolve$.$anonfun$validate$1(Resolve.scala:325)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:273)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:266)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at coursier.Resolve$.validate(Resolve.scala:323)
	at coursier.Resolve.validate0$1(Resolve.scala:112)
	at coursier.Resolve.$anonfun$ioWithConflicts0$4(Resolve.scala:156)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:497)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```
I'm assuming because like it says, there is not actual stable version listed in `versions` [here](https://repo1.maven.org/maven2/com/lihaoyi/mill-dev_2.13/maven-metadata.xml)?

**Comment by alexarchambault** [comment]
That seems to originate from mill having recently switched to scala 2.13, with no stable version for it yet, and limitations of the scala version selection in coursier…

As a workaround, mill can be run with coursier with `cs launch mill --scala 2.12.10 -- …command…` for now.

**Comment by ckipp01** [comment]
Sounds good. Thanks!
