### ISSUE TITLE
Fails to install `scala-update`.

### ISSUE THREAD

**Issue by ckipp01** [coursier/apps#175]
When trying to do a `cs install --contrib scala-update` it fails with the following:

```
warning: unknown anonymous info of class scala.tools.nsc.typechecker.ContextErrors$NamerContextErrors$NamerErrorGen$DuplicatesErrorKinds$, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by scala.tools.nsc.typechecker.ContextErrors$NamerContextErrors$NamerErrorGen$DuplicatesErrorKinds$ which is not following the naming convention.
warning: unknown anonymous info of class scala.tools.nsc.typechecker.ContextErrors$InferencerContextErrors$InferErrorGen$PolyAlternativeErrorKind$, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by scala.tools.nsc.typechecker.ContextErrors$InferencerContextErrors$InferErrorGen$PolyAlternativeErrorKind$ which is not following the naming convention.
warning: unknown anonymous info of class scala.tools.nsc.settings.Warnings$LintWarnings$LintWarning, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by scala.tools.nsc.settings.Warnings$LintWarnings$LintWarning which is not following the naming convention.
warning: unknown anonymous info of class scala.tools.nsc.typechecker.ContextErrors$NamerContextErrors$NamerErrorGen$SymValidateErrors$, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by scala.tools.nsc.typechecker.ContextErrors$NamerContextErrors$NamerErrorGen$SymValidateErrors$ which is not following the naming convention.
warning: unknown anonymous info of class izumi.reflect.macrortti.LightTypeTag$ParsedLightTypeTag$SubtypeDBs, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by izumi.reflect.macrortti.LightTypeTag$ParsedLightTypeTag$SubtypeDBs which is not following the naming convention.
warning: unknown anonymous info of class izumi.reflect.macrortti.LightTypeTagRef$RefinementDecl$Signature, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by izumi.reflect.macrortti.LightTypeTagRef$RefinementDecl$Signature which is not following the naming convention.
warning: unknown anonymous info of class [Lizumi.reflect.macrortti.LightTypeTagRef$RefinementDecl$Signature;, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by [Lizumi.reflect.macrortti.LightTypeTagRef$RefinementDecl$Signature; which is not following the naming convention.
warning: unknown anonymous info of class [[Lizumi.reflect.macrortti.LightTypeTagRef$RefinementDecl$Signature;, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by [[Lizumi.reflect.macrortti.LightTypeTagRef$RefinementDecl$Signature; which is not following the naming convention.
warning: unknown anonymous info of class [[[Lizumi.reflect.macrortti.LightTypeTagRef$RefinementDecl$Signature;, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by [[[Lizumi.reflect.macrortti.LightTypeTagRef$RefinementDecl$Signature; which is not following the naming convention.
warning: unknown anonymous info of class [[[[Lizumi.reflect.macrortti.LightTypeTagRef$RefinementDecl$Signature;, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by [[[[Lizumi.reflect.macrortti.LightTypeTagRef$RefinementDecl$Signature; which is not following the naming convention.
warning: unknown anonymous info of class [[[[[Lizumi.reflect.macrortti.LightTypeTagRef$RefinementDecl$Signature;, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by [[[[[Lizumi.reflect.macrortti.LightTypeTagRef$RefinementDecl$Signature; which is not following the naming convention.
warning: unknown anonymous info of class izumi.reflect.macrortti.LightTypeTagRef$RefinementDecl$TypeMember, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by izumi.reflect.macrortti.LightTypeTagRef$RefinementDecl$TypeMember which is not following the naming convention.
warning: unknown anonymous info of class [Lizumi.reflect.macrortti.LightTypeTagRef$RefinementDecl$TypeMember;, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by [Lizumi.reflect.macrortti.LightTypeTagRef$RefinementDecl$TypeMember; which is not following the naming convention.
warning: unknown anonymous info of class [[Lizumi.reflect.macrortti.LightTypeTagRef$RefinementDecl$TypeMember;, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by [[Lizumi.reflect.macrortti.LightTypeTagRef$RefinementDecl$TypeMember; which is not following the naming convention.
warning: unknown anonymous info of class [[[Lizumi.reflect.macrortti.LightTypeTagRef$RefinementDecl$TypeMember;, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by [[[Lizumi.reflect.macrortti.LightTypeTagRef$RefinementDecl$TypeMember; which is not following the naming convention.
warning: unknown anonymous info of class [[[[Lizumi.reflect.macrortti.LightTypeTagRef$RefinementDecl$TypeMember;, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by [[[[Lizumi.reflect.macrortti.LightTypeTagRef$RefinementDecl$TypeMember; which is not following the naming convention.
warning: unknown anonymous info of class [[[[[Lizumi.reflect.macrortti.LightTypeTagRef$RefinementDecl$TypeMember;, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by [[[[[Lizumi.reflect.macrortti.LightTypeTagRef$RefinementDecl$TypeMember; which is not following the naming convention.
warning: unknown anonymous info of class izumi.reflect.macrortti.LightTypeTagRef$Variance$Covariant$, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by izumi.reflect.macrortti.LightTypeTagRef$Variance$Covariant$ which is not following the naming convention.
warning: unknown anonymous info of class izumi.reflect.macrortti.LightTypeTagRef$Variance$Contravariant$, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by izumi.reflect.macrortti.LightTypeTagRef$Variance$Contravariant$ which is not following the naming convention.
warning: unknown anonymous info of class izumi.reflect.macrortti.LightTypeTagRef$Variance$Invariant$, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by izumi.reflect.macrortti.LightTypeTagRef$Variance$Invariant$ which is not following the naming convention.
warning: unknown anonymous info of class izumi.reflect.macrortti.LightTypeTagRef$SymName$SymTermName, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by izumi.reflect.macrortti.LightTypeTagRef$SymName$SymTermName which is not following the naming convention.
warning: unknown anonymous info of class izumi.reflect.macrortti.LightTypeTagRef$SymName$SymTypeName, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by izumi.reflect.macrortti.LightTypeTagRef$SymName$SymTypeName which is not following the naming convention.
warning: unknown anonymous info of class izumi.reflect.macrortti.LightTypeTagRef$SymName$SymLiteral, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by izumi.reflect.macrortti.LightTypeTagRef$SymName$SymLiteral which is not following the naming convention.
warning: unknown anonymous info of class zio.Fiber$Runtime$Internal, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by zio.Fiber$Runtime$Internal which is not following the naming convention.
warning: unknown anonymous info of class izumi.reflect.macrortti.LightTypeTagRef$Boundaries$Defined, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by izumi.reflect.macrortti.LightTypeTagRef$Boundaries$Defined which is not following the naming convention.
warning: unknown anonymous info of class izumi.reflect.macrortti.LightTypeTagRef$Boundaries$Empty$, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by izumi.reflect.macrortti.LightTypeTagRef$Boundaries$Empty$ which is not following the naming convention.
warning: unknown anonymous info of class zio.internal.FiberRuntime$EvaluationSignal$Continue$, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by zio.internal.FiberRuntime$EvaluationSignal$Continue$ which is not following the naming convention.
warning: unknown anonymous info of class zio.internal.FiberRuntime$EvaluationSignal$Done$, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by zio.internal.FiberRuntime$EvaluationSignal$Done$ which is not following the naming convention.
warning: unknown anonymous info of class zio.internal.FiberRuntime$EvaluationSignal$YieldNow$, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by zio.internal.FiberRuntime$EvaluationSignal$YieldNow$ which is not following the naming convention.
warning: unknown anonymous info of class zio.Fiber$Status$Done$, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by zio.Fiber$Status$Done$ which is not following the naming convention.
warning: unknown anonymous info of class zio.Fiber$Status$Unfinished, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by zio.Fiber$Status$Unfinished which is not following the naming convention.
warning: unknown anonymous info of class zio.Fiber$Status$Running, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by zio.Fiber$Status$Running which is not following the naming convention.
warning: unknown anonymous info of class zio.Fiber$Status$Suspended, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by zio.Fiber$Status$Suspended which is not following the naming convention.
warning: unknown anonymous info of class zio.ZIO$EvaluationStep$UpdateRuntimeFlags, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by zio.ZIO$EvaluationStep$UpdateRuntimeFlags which is not following the naming convention.
warning: unknown anonymous info of class zio.ZIO$EvaluationStep$UpdateTrace, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by zio.ZIO$EvaluationStep$UpdateTrace which is not following the naming convention.
warning: unknown anonymous info of class zio.ZIO$EvaluationStep$UpdateRuntimeFlags$, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by zio.ZIO$EvaluationStep$UpdateRuntimeFlags$ which is not following the naming convention.
warning: unknown anonymous info of class zio.ZIO$EvaluationStep$Continuation$, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by zio.ZIO$EvaluationStep$Continuation$ which is not following the naming convention.
warning: unknown anonymous info of class zio.ZIO$ZIOError$Traced, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by zio.ZIO$ZIOError$Traced which is not following the naming convention.
warning: unknown anonymous info of class zio.ZIO$UpdateRuntimeFlagsWithin$Dynamic, assuming class is not anonymous. To remove the warning report an issue to the library or language author. The issue is caused by zio.ZIO$UpdateRuntimeFlagsWithin$Dynamic which is not following the naming convention.
[/Users/ckipp/Library/Application Support/Coursier/bin/.scala-update.aux.part:83711]     analysis:   9,361.34 ms
Error: Classes that should be initialized at run time got initialized during image building:
 scala.runtime.Statics was unintentionally initialized at build time. To see why scala.runtime.Statics got initialized use -H:+TraceClassInitialization

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
Exception in thread "main" java.lang.RuntimeException: Error running native-image (exit code: 1)
        at scala.sys.package$.error(package.scala:30)
        at coursier.launcher.NativeImageGenerator$.generate(NativeImageGenerator.scala:124)
        at coursier.launcher.Generator$.generate(Generator.scala:14)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$15(InstallDir.scala:342)
        at coursier.install.InstallDir$.coursier$install$InstallDir$$writing(InstallDir.scala:570)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$14(InstallDir.scala:341)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$14$adapted(InstallDir.scala:311)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$22(InstallDir.scala:417)
        at coursier.install.InstallDir.$anonfun$createOrUpdate$22$adapted(InstallDir.scala:416)
        at coursier.install.Updatable$.get$1(Updatable.scala:61)
        at coursier.install.Updatable$.$anonfun$writing$1(Updatable.scala:106)
        at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:71)
        at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:95)
        at coursier.install.Updatable$.writing(Updatable.scala:106)
        at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:416)
        at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:96)
        at coursier.cli.install.Install$.$anonfun$run$7(Install.scala:127)
        at coursier.cli.install.Install$.$anonfun$run$7$adapted(Install.scala:114)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at coursier.cli.install.Install$.run(Install.scala:114)
        at coursier.cli.install.Install$.run(Install.scala:22)
        at caseapp.core.app.CaseApp.main(CaseApp.scala:149)
        at caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:115)
        at coursier.cli.Coursier$.main(Coursier.scala:118)
        at coursier.cli.Coursier.main(Coursier.scala)
```

- cs version: 2.1.0-M7-18-g67daad6a9
- os: macOS Monterey 12.6
- Java version: openjdk 17.0.4

CC @kitlangton

**Comment by alexarchambault** [comment]
It fails because it tries to build a native binary locally (and building native images with coursier should be deprecated IMO). That feature needs to be disabled (`cs install` should either install a pre-built binary, or fail).
